# fly.toml app configuration file generated for hue-hub on 2023-07-11T11:15:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hue-hub"
primary_region = "fra"
console_command = "/rails/bin/rails console"

[deploy]
  release_command = "./bin/rails db:prepare"

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
